<?php
$statusErrors = [
    'userBloqueado' => 'Maximo de intentos alcanzados, usuario bloqueado. Comunicate con el administrador',
    'userDesabilitado' => 'Usuario Deshabilitado',
    'success' => 'Contraseña Actualizada Correctamente, ahora puedes iniciar sesión',
    'userPass' => 'La contraseña o el correo son incorrectos',
    'userNone' => 'No se encontró ningún usuario con el correo electrónico proporcionado',
    'consultaPrep' => 'Error en la preparación y ejecución de la consulta',
    'dtaError' => 'No se ingresó correctamente el correo electrónico o la clave',
    'sessionCad' => 'Sesión caducada, ingresa de nuevo tus credenciales',
    'dataError' => 'Error al encontrar correo y enviar contraseña temporal',
    'timePassCad' => 'Contraseña temporal expirada, crea una nueva mente',
    'coreoInEXT' => 'Correo inexistente, verifica e intenta de nuevo',
    'complete' => 'Actualización exitosa de la contraseña, ingresa al SIA',
    'errorConsulta' => 'Error al actualizar la contraseña',
    'contraCaducada' => 'Tu contraseña ha caducado, intenta más tarde',
    'errorUsuario' => 'No se encontró al usuario',
    'contraDiferentes' => 'Las contraseñas no coinciden',
    'correoEnvErr' => 'Error al enviar el correo con la clave temporal',
    'errorContTEnv' => 'Contraseña temporal no generada, intenta de nuevo',
    'contraTemporalError' => 'Tu contraseña temporal no es correcta, intenta de nuevo',
    'noResult' => 'sin registros se contraseña temporal',
    'userBloq' => 'maximo numero de intentos alcanzado. Usuario bloqueado, comunicate con el administrador',
    'statusBloq' => 'Error al actualizar el status_bloqueo',
    'SinData' => 'No Hay datos que procesar',
    'IdiomamErr' => 'No Seleccionaste un Idioma',
    'InsertSuccess' => 'Datos insertados Correctamente, Puedes continuar',
    'ArchivoDownload' => 'Archivo Data Excel descargado y creado Correctamente',
    'ArchivoNull' => 'Archivo Data Excel no Generado Actualmente',
    'errPrepConsult' => 'Error en la preparación de la consulta',
    'DataComplete' => 'Datos Recolectados con Exito',
    'ErrXls' => 'Error al abrir la hoja del archivo Excel',
    'ErrCopyXls' => 'Error al crear la copia del archivo',
    'IdiomaBlock' => 'Los Datos de este idioma ya fueron enviados, intenta con otro'
];
?>